theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "time"
format = "%a %d/%m %R"
timezone = "US/Pacific"
interval = 60

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "net"
device = "eno1"
ssid = true
ip = true
speed_up = false
graph_up = false
interval = 1

[[block]]
block = "net"
device = "wlo1"
ssid = true
ip = true
speed_up = false
graph_up = false
interval = 1

[[block]]
block = "music"
buttons = ["play", "next"]

[[block]]
block = "memory"
format_mem = "{Mum}MB/{MTm}MB({Mup}%)"
format_swap = "{SUm}MB/{STm}MB({SUp}%)"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "cpu"
interval = 1
frequency = true

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"
